### PR TITLE
QUIC clarification

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Comment by zaheduzzaman** [comment]
This looks good too me, however, there is no guarantee about the QUIC metric draft referred here. Hence,  we can leave that out now. I also think the fact that this draft only covers protocol based on RFC 8329, it might worth mentioning.

**Comment by boucadair** [comment]
> This looks good too me, however, there is no guarantee about the QUIC metric draft referred here. Hence, we can leave that out now. 

That's why the proposed text uses "e.g.". The intent of providing the pointer is to have an evidence that the specs are not stable yet.

>  I also think the fact that this draft only covers protocol based on RFC 8329, it might worth mentioning.

I guess you meant 8312, no? 

A note can be added to repeat what is already in the table.

**Comment by zaheduzzaman** [comment]
> I guess you meant 8312, no?

No, There is a table in 8329 which lists the L4 protocols, and as I understand from the response to my comment this draft is covering protocols from that list. Hence, QUIC was not initially involved what this spec was worked on.

**Comment by boucadair** [comment]
> > I guess you meant 8312, no?
> 
> No, There is a table in 8329 which lists the L4 protocols, and as I understand from the response to my comment this draft is covering protocols from that list. Hence, QUIC was not initially involved what this spec was worked on.

I may be missing something, but I don't find in the archives where 8329 was called in the discussion for this draft. Can you please share a pointer? Thank you, Zahed.

**Comment by zaheduzzaman** [comment]
> > > I guess you meant 8312, no?
> > 
> > 
> > No, There is a table in 8329 which lists the L4 protocols, and as I understand from the response to my comment this draft is covering protocols from that list. Hence, QUIC was not initially involved what this spec was worked on.
> 
> I may be missing something, but I don't find in the archives where 8329 was called in the discussion for this draft. Can you please share a pointer? Thank you, Zahed.

ignore my comment about RFC 8329, I mixed it up with another discussion I am having. Sorry about about it.

**Pull request merged**
